version: "3"

services:
    api:
        container_name: medical-leaf-api
        build: ./src/api
        image: hiseulgi/medical-leaf-api:latest
        restart: always
        ports:
            - ${API_PORT}:${API_PORT}
        expose:
            - ${API_PORT}
        volumes:
            - ./:/app
            - /etc/localtime:/etc/localtime:ro
        command: python src/api/main.py

    web:
        container_name: medical-leaf-web
        build: ./src/web
        image: hiseulgi/medical-leaf-web:latest
        restart: always
        ports:
            - ${WEB_PORT}:${WEB_PORT}
        expose:
            - ${WEB_PORT}
        volumes:
            - ./:/app
            - /etc/localtime:/etc/localtime:ro
        command: streamlit run src/web/main.py --server.port=${WEB_PORT} --server.address=0.0.0.0
        