version: "3"

services:
  api:
    container_name: medical-leaf-api
    build: ./src/api
    image: hiseulgi/medical-leaf-api:latest
    restart: always
    ports:
        - ${API_PORT}:${API_PORT}
    expose:
        - ${API_PORT}
    volumes:
        - ./:/app
        - /etc/localtime:/etc/localtime:ro
    command: python src/api/main.py